# Generated by Django 4.2.2 on 2023-07-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, choices=[('p', 'Pasta'), ('D', 'Digital')], default='P', max_length=1),
        ),
    ]
