# Generated by Django 4.2.2 on 2023-07-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite_color',
            field=models.CharField(blank=True, choices=[(1, 'Azul'), (2, 'Rojo'), (3, 'Amarillo'), (4, 'Verde')], default='', max_length=225),
        ),
    ]
